### ISSUE TITLE
show config file value doesn't work for non-numeric LineHeight values

### ISSUE THREAD

**Issue by sjaakbanaan** [chakra-ui/panda-vscode#40]
### Description

So this works fine, i can see the color values and the actual base font-size:
![image](https://github.com/chakra-ui/panda-vscode/assets/2773301/2064daed-72f6-4c64-b5fe-83009642edca)

This stops working as soon as i add LineHeight with a non-numeric value:
![image](https://github.com/chakra-ui/panda-vscode/assets/2773301/a838dc83-f46d-46df-a80a-c920f9322a62)

### Link to Reproduction

https://

### Steps to reproduce

1. Open a component with the `cva()` function in VS Code;
2. Add a lineHeight to it, without a numeric value.

### JS Framework

React

### Panda CSS Version

^0.30.2

### Browser

/

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@sjaakbanaan could you attach a reproduction of your specific issue at https://play.panda-css.com/? Thanks.

**Comment by anubra266** [comment]
Ah sorry @sjaakbanaan I thought this was the panda repo 😁

**Comment by sjaakbanaan** [comment]
> Ah sorry @sjaakbanaan I thought this was the panda repo 😁

Haha no problem, I was already wondering how i was going to reproduce the issue there 😁
