### ISSUE TITLE
v0.4.17162046 (pre-release) crashes directly

### ISSUE THREAD

**Issue by sjaakbanaan** [chakra-ui/panda-vscode#51]
### Description

When I start VS code since the last pre-release version from 1 hour ago, it won't load at all, because it stops the server since it crashes more than 5 times in 3 minutes. The error i get is: 
`"Panda IntelliSense client: couldn't create connection to server."`

In the output I see it also misses a module:
`Error: Cannot find module '@vue/compiler-sfc'`

### Link to Reproduction

http://

### Steps to reproduce

Update to v0.4.17162046 on a clean machine.

### JS Framework

React / JS

### Panda CSS Version

0.30.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
sorry about that, on it, please stay on the previous version in the meantime 🙏

**Comment by astahmer** [comment]
that should be fixed, seems fine now with `v0.4.17162781 (pre-release)`

**Comment by sjaakbanaan** [comment]
Thanks, and no problem of course. After all, it's still labelled as a preview-release :)
